services:
  - type: web
    name: molorr-server-t34o
    runtime: docker
    repo: https://github.com/tryoooooofff/Molorr
    rootDir: develop-multiplayer-canvas2d-game
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_GAME_WS
        value: wss://molorr-server-t34o.onrender.com
      - key: DATABASE_URL
        sync: false

  - type: web
    name: molorr-server-sg
    runtime: docker
    repo: https://github.com/tryoooooofff/Molorr
    rootDir: develop-multiplayer-canvas2d-game
    dockerfilePath: Dockerfile
    region: singapore
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_GAME_WS
        value: wss://molorr-server-sg.onrender.com
      - key: DATABASE_URL
        sync: false

  - type: web
    name: molorr-server-hk
    runtime: docker
    repo: https://github.com/tryoooooofff/Molorr
    rootDir: develop-multiplayer-canvas2d-game
    dockerfilePath: Dockerfile
    region: hong kong
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_GAME_WS
        value: wss://molorr-server-hk.onrender.com
      - key: DATABASE_URL
        sync: false