// Authoritative game simulation. Runs on the node/ws server (server/index.ts)
// and, when no remote server is configured, inside the browser (local transport).

import {
  AFK_CHECK_SECONDS,
  AFK_IDLE_SECONDS,
  BAG_COUNT,
  BAG_MAX,
  BLOCK_GRID_COLS,
  BLOCK_GRID_ROWS,
  CRAFT_CARD_COUNT,
  CRAFT_CARDS_PER_ATTEMPT,
  craftChanceFor,
  EMPTY_ITEM,
  ITEMS,
  MAPS,
  MAX_CRAFT_RARITY,
  MAX_RARITY,
  MOBS,
  CLOVER_ITEM,
  orbitsAsPetal,
  DNA_UPGRADE_BASE_CHANCE,
  DROP_STACK_MAX,
  DROP_STACK_RADIUS,
  DROP_TRIM_COUNT,
  MAGIC_CORE_ITEM,
  MAGIC_ITEM_MAP,
  MAX_DROPPED_CARDS,
  cloverDnaBonus,
  mapRarityToSummonRarity,
  mobSizeMult,
  friendlyMobSizeMult,
  ORACLE_COOLDOWN_HOURS,
  ORACLE_SKIP,
  oracleRequiredCount,
  RARITIES,
  ROSE_ABSORB_TIME,
  ROSE_HEAL_DELAY,
  SHELL_ITEM,
  isAbsorbItem,
  SECONDARY_SLOT_COUNT,
  HOTBAR_CELLS,
  isBagCell,
  isHotbarCell,
  isMainCell,
  SLOT_COUNT,
  TOTAL_CELLS,
  TRADE_COOLDOWN_HOURS,
  TRINKET_ITEM,
  Wall,
  enemyRarityMult,
  enemyDamageMult,
  getBlockAt,
  getDropRarityByItem,
  getSpawnProtection,
  getSummonBatch,
  getSummonCount,
  levelFromXp,
  rarityMult,
  rollZoneRarity,
  findSpawnTiles,
  thirdEyeOrbitBonus,
} from "./defs";
import { C2S, ENT, EVT, Reader, S2C, SWAP_ROW_ALL, TEAM, Writer } from "./protocol";

// =====================================================================
// Squad system
// =====================================================================

interface SquadMember {
  clientId: number;
  playerId: number;
  name: string;
  level: number;
}

interface Squad {
  code: string;
  isPublic: boolean;
  members: Map<number, SquadMember>; // key = playerId
  createdAt: number;
}

/** Maximum level gap between squad members */
const SQUAD_LEVEL_GAP_MAX = 30;

/** Maximum members per squad */
const SQUAD_MAX_MEMBERS = 4;

/** Squad code length */
const SQUAD_CODE_LENGTH = 6;

export interface Cell {
  item: number;
  rarity: number;
  count: number;
}

/** Player hit-radius / body size. Scaled to 70% of the original 26px. */
export const PLAYER_RADIUS = 26 * 0.7;

interface PetalState {
  id: number;
  alive: boolean;
  hp: number;
  maxHp: number;
  timer: number;
  x: number;
  y: number;
  hitCd: number;
  /** Delay before a freshly spawned Rose is allowed to heal. */
  specialTimer: number;
  /** Remaining travel time while a Rose is being absorbed by its owner. */
  absorbTimer: number;
}

export interface PlayerSave {
  slots: (Cell | null)[];
  /** Backup hotbar row. Same length as `slots`; never spawns petals. */
  secondary: (Cell | null)[];
  bag: (Cell | null)[];
  xp: number;
  mapId: number;
  /** Epoch ms timestamp of the next allowed Oracle use (0 = ready now). */
  nextOracleAt?: number;
  /** Epoch ms timestamp of the next allowed Trade use (0 = ready now). */
  nextTradeAt?: number;
}

export class Player {
  id: number;
  name = "flower";
  mapId = 0;
  x = 0;
  y = 0;
  vx = 0;
  vy = 0;
  hp = 120;
  maxHp = 120;
  xp = 0;
  level = 1;
  alive = true;
  respawnIn = 0;
  inDx = 0;
  inDy = 0;
  flags = 0;
  baseAngle = 0;
  orbit = 62;
  nextOracleAt = 0;
  nextTradeAt = 0;
  /** Daily-bonus state supplied by the local-progress client. */
  bonusMultiplier = 1;
  bonusEndsAt = 0;
  /** Squad code this player belongs to (empty string = no squad). */
  squadCode = "";
  slots: (Cell | null)[] = new Array(SLOT_COUNT).fill(null);
  /**
   * Secondary hotbar row. It holds real items but never grows petals — it is
   * pure standby storage that can be swapped into the main row instantly.
   */
  secondary: (Cell | null)[] = new Array(SECONDARY_SLOT_COUNT).fill(null);
  bag: (Cell | null)[] = new Array(BAG_COUNT).fill(null);
  petals: PetalState[] = [];
  pets: Mob[][] = Array.from({ length: SLOT_COUNT }, () => []);
  hurtCd = 0;
  /** Shield points (1 shield absorbs 2 damage). Generated by Shell petals. */
  shield = 0;
  dirty = true;
  statsDirty = true;

  // =====================================================================
  // Bubble: defend-key rising-edge detection
  // =====================================================================
  /** Previous tick's defend flag, used to detect a fresh press of Shift/Contract. */
  wasDefending = false;

  constructor(id: number) {
    this.id = id;
  }
}

export class Mob {
  id: number;
  type: number;
  mapId: number;
  x: number;
  y: number;
  vx = 0;
  vy = 0;
  hp: number;
  maxHp: number;
  angle = 0;
  rarity: number;
  friendly: boolean;
  ownerId = 0;
  ownerSlot = -1;
  /** Summon item id that hatched this friendly mob, or -1 for wild mobs. */
  sourceItem = -1;
  /** Rarity of the summon item that hatched this friendly mob. */
  sourceRarity = 0;
  targetId = 0;
  wander = 0;
  hitCd = 0;
  radius: number;
  damage: number;
  speed: number;
  lastHitBy = 0;
  /** Seconds of post-spawn invulnerability. Freshly hatched pets get a moment to get clear. */
  spawnProtection = 0;
  /** HP-fraction thresholds that have already released their minions (spawner mobs only). */
  spawnedThresholds: Set<number> = new Set();
  /** Accumulated damage dealt by each player (petal + friendly mob damage). */
  damageByPlayer: Map<number, number> = new Map();

  constructor(
    id: number,
    type: number,
    mapId: number,
    x: number,
    y: number,
    rarity: number,
    friendly = false
  ) {
    const def = MOBS[type];
    // Player-owned summons scale like petals (rarityMult); wild mobs scale on the steeper enemy curve.
    const m = friendly ? rarityMult(rarity) : enemyRarityMult(rarity);
    this.id = id;
    this.type = type;
    this.mapId = mapId;
    this.x = x;
    this.y = y;
    this.rarity = rarity;
    this.friendly = friendly;
    this.maxHp = Math.round(def.health * m);
    this.hp = this.maxHp;
    // Mob rarity controls physical size as well as its combat stats. Keeping
    // this radius authoritative means rendering, wall collision, melee range,
    // and mob-to-mob collision all agree on the requested size ladder.
    this.radius = def.radius * (friendly ? friendlyMobSizeMult(rarity) : mobSizeMult(rarity));
    this.damage = def.damage * enemyDamageMult(rarity);
    this.speed = def.speed;
  }

  addDamage(playerId: number, amount: number) {
    if (!playerId || amount <= 0) return;
    this.damageByPlayer.set(playerId, (this.damageByPlayer.get(playerId) || 0) + amount);
  }

}

export class Drop {
  /** Set of playerIds allowed to loot this drop. null = anyone, empty = no one (unlootable). */
  allowedPlayerIds: Set<number> | null = null;
  constructor(
    public id: number,
    public mapId: number,
    public x: number,
    public y: number,
    public item: number,
    public rarity: number,
    public ownerId = 0,
    public ttl = 45,
    /** Cards merged into one card. Nearby identical drops stack instead of littering. */
    public count = 1
  ) {}
}

interface World {
  mobs: Mob[];
  drops: Drop[];
}

export interface ClientLike {
  send(data: Uint8Array): void;
}

interface ClientState {
  send(data: Uint8Array): void;
  player: Player | null;
  events: Uint8Array[];
  /** Seconds since the last meaningful (non-neutral) client action. */
  idleSeconds: number;
  /** True once the [AFK CHECK] button has been shown and is awaiting a click. */
  afkPending: boolean;
  /** Seconds left on the visible AFK countdown; only meaningful while pending. */
  afkSecondsLeft: number;
  /** Last countdown value pushed to the client, so we only resend on change. */
  afkLastSent: number;
  /** Set by the AFK sweep; the host closes the socket on the next drain. */
  kick: boolean;
  /** Last INPUT payload seen, so only a *change* in input counts as activity. */
  lastInDx: number;
  lastInDy: number;
  lastFlags: number;
}

function clamp(v: number, a: number, b: number) {
  return v < a ? a : v > b ? b : v;
}

/**
 * Mutable counter threaded through the collision helpers below so
 * `GameServer` can report a live "collision checks per tick" debug metric
 * without every call site needing to know about it individually.
 */
export interface CollisionCounter {
  n: number;
}

// ---------------------------------------------------------------------
// Spatial Hashing for Walls (Static)
// ---------------------------------------------------------------------

// =====================================================================
// Polygon-based Wall Collider with BVH (O(log n) queries)
// 多边形噪声墙壁 + 层次包围盒碰撞系统
// =====================================================================

interface WallEdge {
  x1: number; y1: number;
  x2: number; y2: number;
  nx: number; ny: number;   // 预计算外法线（单位向量）
  len: number;
}

interface AABB {
  minX: number; minY: number;
  maxX: number; maxY: number;
}

interface BVHNode {
  aabb: AABB;
  left: BVHNode | null;
  right: BVHNode | null;
  edges: WallEdge[] | null;  // 仅叶子节点存储边
}

interface GridCell {
  edges: WallEdge[];
}

class PolygonWallCollider {
  private polygons: { x: number; y: number }[][] = [];
  private edges: WallEdge[] = [];
  private bvh: BVHNode | null = null;
  private spatialGrid: Map<string, GridCell> = new Map();
  private gridCellSize: number;
  private mapWidth: number;
  private mapHeight: number;
  private gridCols: number;
  private gridRows: number;
  wallMaxJitterPx = 0;

  // 调试统计
  bvhNodeCount = 0;
  bvhLeafCount = 0;
  bvhMaxDepth = 0;

  constructor(
    walls: Wall[],
    mapWidth: number,
    mapHeight: number,
    gridResolution: number = 256,
    private maxEdgesPerLeaf: number = 8
  ) {
    this.mapWidth = mapWidth;
    this.mapHeight = mapHeight;
    this.gridCellSize = Math.max(mapWidth, mapHeight) / gridResolution;
    this.gridCols = Math.ceil(mapWidth / this.gridCellSize);
    this.gridRows = Math.ceil(mapHeight / this.gridCellSize);

    // =========================
    // 预处理阶段（服务器启动一次性完成）
    // =========================
    const t0 = performance.now();

    // 1. AABB 墙壁栅格化为二进制网格
    const grid = this.rasterizeWalls(walls, gridResolution);

    // 2. 提取有向轮廓边（逆时针闭合多边形）
    const loops = this.extractContours(grid, gridResolution);

    // 3. 简化：剔除共线中间点
    const simplified = loops.map(l => this.simplifyLoop(l));

    // 4. 加噪声并转换到世界坐标
    const cellW = mapWidth / gridResolution;
    const cellH = mapHeight / gridResolution;
    this.polygons = simplified.map((loop, idx) =>
      this.addNoise(loop, idx, cellW, cellH)
    );

    // 5. 构建带预计算法线的边表
    for (const poly of this.polygons) {
      const n = poly.length;
      for (let i = 0; i < n; i++) {
        const p1 = poly[i];
        const p2 = poly[(i + 1) % n];
        const dx = p2.x - p1.x;
        const dy = p2.y - p1.y;
        const len = Math.hypot(dx, dy);
        if (len < 0.001) continue;
        // 外法线：轮廓为逆时针，(-dy, dx) 朝外
        const nx = -dy / len;
        const ny = dx / len;
        this.edges.push({ x1: p1.x, y1: p1.y, x2: p2.x, y2: p2.y, nx, ny, len });
      }
    }

    // 6. 构建 BVH 层次包围盒
    this.bvh = this.buildBVH(this.edges);

    // 7. 构建空间网格（作为 broad-phase 备选/兼容层）
    this.buildSpatialGrid();

    const t1 = performance.now();
    console.log(
      `[PolygonWallCollider] Preprocessed ${walls.length} walls => ` +
      `${this.edges.length} edges, ${this.bvhNodeCount} BVH nodes ` +
      `(${this.bvhLeafCount} leaves, depth ${this.bvhMaxDepth}), ` +
      `${this.spatialGrid.size} grid cells. ` +
      `Took ${(t1 - t0).toFixed(2)}ms`
    );
  }

  // 1. 栅格化：将 AABB 墙壁填充到二进制网格
  private rasterizeWalls(walls: Wall[], size: number): Uint8Array {
    const grid = new Uint8Array(size * size);
    const cellW = this.mapWidth / size;
    const cellH = this.mapHeight / size;

    for (const w of walls) {
      const x0 = Math.max(0, Math.floor(w.x / cellW));
      const y0 = Math.max(0, Math.floor(w.y / cellH));
      const x1 = Math.min(size - 1, Math.floor((w.x + w.w) / cellW));
      const y1 = Math.min(size - 1, Math.floor((w.y + w.h) / cellH));
      for (let y = y0; y <= y1; y++) {
        for (let x = x0; x <= x1; x++) {
          grid[y * size + x] = 1;
        }
      }
    }
    return grid;
  }

  // 2. 轮廓提取：栅格 → 有向边 → 闭合多边形
  private extractContours(grid: Uint8Array, size: number): { x: number; y: number }[][] {
    const W = (x: number, y: number) =>
      x >= 0 && y >= 0 && x < size && y < size && grid[y * size + x] === 1;

    const edgeMap = new Map<number, { x: number; y: number }>();
    const keyOf = (x: number, y: number) => x * (size + 1) + y;

    for (let y = 0; y < size; y++) {
      for (let x = 0; x < size; x++) {
        if (!W(x, y)) continue;
        if (!W(x, y - 1)) edgeMap.set(keyOf(x, y), { x: x + 1, y });
        if (!W(x + 1, y)) edgeMap.set(keyOf(x + 1, y), { x: x + 1, y: y + 1 });
        if (!W(x, y + 1)) edgeMap.set(keyOf(x + 1, y + 1), { x, y: y + 1 });
        if (!W(x - 1, y)) edgeMap.set(keyOf(x, y + 1), { x, y });
      }
    }

    const rawLoops: { x: number; y: number }[][] = [];
    const visited = new Set<number>();

    for (const startKey of edgeMap.keys()) {
      if (visited.has(startKey)) continue;
      const loop: { x: number; y: number }[] = [];
      let curKey = startKey;
      let guard = 0;
      while (!visited.has(curKey) && guard++ < size * size * 4) {
        visited.add(curKey);
        loop.push({ x: Math.floor(curKey / (size + 1)), y: curKey % (size + 1) });
        const next = edgeMap.get(curKey);
        if (!next) break;
        curKey = keyOf(next.x, next.y);
      }
      if (loop.length >= 3) rawLoops.push(loop);
    }
    return rawLoops;
  }

  // 3. 简化：剔除共线中间点
  private simplifyLoop(loop: { x: number; y: number }[]): { x: number; y: number }[] {
    const n = loop.length;
    const out: { x: number; y: number }[] = [];
    for (let i = 0; i < n; i++) {
      const p0 = loop[(i - 1 + n) % n];
      const p1 = loop[i];
      const p2 = loop[(i + 1) % n];
      const collinear =
        (p1.x - p0.x) * (p2.y - p1.y) === (p1.y - p0.y) * (p2.x - p1.x);
      if (!collinear) out.push(p1);
    }
    return out.length >= 3 ? out : loop;
  }

    private addNoise(
    loop: { x: number; y: number }[],
    loopIdx: number, // 保留参数以兼容调用，但内部不再使用
    cellW: number,
    cellH: number
  ): { x: number; y: number }[] {
    // 1. 优化后的噪声函数：去掉了 seed 参数，直接基于坐标计算
    // 这保证了全地图的噪声风格统一
    const noise = (x: number, y: number) => {
      // 使用大质数防止产生规律性
      let h = x * 374761393 + y * 668265263;
      h = (h ^ (h >> 13)) * 1274126177;
      h = h ^ (h >> 16);
      return (h & 0x7fffffff) / 0x7fffffff;
    };

    // 2. 参数配置
    const PTS_PER_CELL = 1;  // 原值是 7。改为 0.5 意味着“每2个单位才产生一个点”。
                                // 8000 的长度将只生成 4000 个点（原来是 56000+ 个），压力骤减。

    const BIG_AMP = 0.4;       // 保持或稍微增大。点变少了，每个点的波动要稍微明显一点才看得出效果。
    const FINE_AMP = 0.2;      // 保持或稍微增大。同上，细节波动要明显一点。

    const BIG_FREQ = 0.08;     // 降低频率。原来的 0.1 在长距离上会产生很多波动，降低它可以减少计算次数。
    const FINE_FREQ = 1.8;

    const pts: { x: number; y: number }[] = [];
    const n = loop.length;

    for (let i = 0; i < n; i++) {
      const p1 = loop[i];
      const p2 = loop[(i + 1) % n];
      const horizontal = p1.y === p2.y;
      const len = horizontal ? Math.abs(p2.x - p1.x) : Math.abs(p2.y - p1.y);

      // 限制最大步数，防止超长墙壁产生过多顶点
      const steps = Math.max(1, Math.min(Math.round(len * PTS_PER_CELL), 200));

      for (let s = 0; s < steps; s++) {
        const t = s / steps;
        const wx = p1.x + (p2.x - p1.x) * t;
        const wy = p1.y + (p2.y - p1.y) * t;

        let j = 0;
        if (s !== 0) { // 跳过顶点，保持角落锐利
          // 【核心修改】传入坐标作为噪声种子，不再传 loopIdx
            const big = (noise(Math.floor(wx * BIG_FREQ * 1000), Math.floor(wy * BIG_FREQ * 1000)) - 0.5) * 2 * BIG_AMP;
            const fine = (noise(Math.floor(wx * FINE_FREQ * 1000), Math.floor(wy * FINE_FREQ * 1000)) - 0.5) * 2 * FINE_AMP;
          j = big + fine;
        }

        pts.push({
          x: (wx + (horizontal ? 0 : j)) * cellW,
          y: (wy + (horizontal ? j : 0)) * cellH,
        });
      }
    }

    // 更新最大抖动值
    this.wallMaxJitterPx = Math.max(
      this.wallMaxJitterPx,
      (BIG_AMP + FINE_AMP) * Math.min(cellW, cellH)
    );
    return pts;
  }

  // 5. BVH 构建（SAH 中位分割）
  private buildBVH(edges: WallEdge[]): BVHNode | null {
    if (edges.length === 0) return null;
    return this.buildBVHRecursive(edges, 0);
  }

  private buildBVHRecursive(edges: WallEdge[], depth: number): BVHNode {
    this.bvhNodeCount++;
    this.bvhMaxDepth = Math.max(this.bvhMaxDepth, depth);

    const aabb = this.computeEdgesAABB(edges);

    if (edges.length <= this.maxEdgesPerLeaf) {
      this.bvhLeafCount++;
      return { aabb, left: null, right: null, edges };
    }

    const extentX = aabb.maxX - aabb.minX;
    const extentY = aabb.maxY - aabb.minY;
    const axis = extentX >= extentY ? 0 : 1;

    const sorted = edges.slice().sort((a, b) => {
      const ca = axis === 0 ? (a.x1 + a.x2) * 0.5 : (a.y1 + a.y2) * 0.5;
      const cb = axis === 0 ? (b.x1 + b.x2) * 0.5 : (b.y1 + b.y2) * 0.5;
      return ca - cb;
    });

    const mid = Math.floor(sorted.length / 2);
    const left = this.buildBVHRecursive(sorted.slice(0, mid), depth + 1);
    const right = this.buildBVHRecursive(sorted.slice(mid), depth + 1);

    return { aabb, left, right, edges: null };
  }

  private computeEdgesAABB(edges: WallEdge[]): AABB {
    let minX = Infinity, minY = Infinity;
    let maxX = -Infinity, maxY = -Infinity;
    for (const e of edges) {
      minX = Math.min(minX, e.x1, e.x2);
      minY = Math.min(minY, e.y1, e.y2);
      maxX = Math.max(maxX, e.x1, e.x2);
      maxY = Math.max(maxY, e.y1, e.y2);
    }
    return { minX, minY, maxX, maxY };
  }

  // 6. 空间网格（broad-phase / 兼容层）
  private buildSpatialGrid() {
    for (const e of this.edges) {
      const x0 = Math.floor(Math.min(e.x1, e.x2) / this.gridCellSize);
      const y0 = Math.floor(Math.min(e.y1, e.y2) / this.gridCellSize);
      const x1 = Math.floor(Math.max(e.x1, e.x2) / this.gridCellSize);
      const y1 = Math.floor(Math.max(e.y1, e.y2) / this.gridCellSize);

      for (let gy = y0; gy <= y1; gy++) {
        for (let gx = x0; gx <= x1; gx++) {
          const key = `${gx},${gy}`;
          let cell = this.spatialGrid.get(key);
          if (!cell) {
            cell = { edges: [] };
            this.spatialGrid.set(key, cell);
          }
          cell.edges.push(e);
        }
      }
    }
  }

  // =========================
  // 7. 碰撞查询 API
  // =========================

  /** 圆与多边形墙壁碰撞检测（主 API）。使用 BVH 快速排除，平均 O(log n)。 */
  collideCircle(x: number, y: number, r: number, counter?: CollisionCounter): [number, number] {
    if (!this.bvh) return [x, y];
    for (let pass = 0; pass < 3; pass++) {
      let moved = false;
      const candidates = this.queryBVH(this.bvh, x, y, r, counter);
      for (const e of candidates) {
        if (counter) counter.n++;
        const result = this.circleSegmentCollide(x, y, r, e);
        if (result) {
          moved = true;
          x = result.x;
          y = result.y;
        }
      }
      if (!moved) break;
    }
    return [x, y];
  }

  /** 带移动步进的圆碰撞（防止高速穿透）。 */
  moveCircle(
    x: number, y: number, dx: number, dy: number, r: number, counter?: CollisionCounter
  ): [number, number] {
    const dist = Math.hypot(dx, dy);
    const maxStep = Math.max(4, r * 0.45);
    const steps = Math.max(1, Math.ceil(dist / maxStep));
    const sx = dx / steps;
    const sy = dy / steps;
    for (let i = 0; i < steps; i++) {
      x += sx;
      y += sy;
      [x, y] = this.collideCircle(x, y, r, counter);
    }
    return [x, y];
  }

  /** 兼容旧接口：获取某位置附近的墙壁边（空间网格查询）。 */
  getWallsNear(x: number, y: number, radius: number): WallEdge[] {
    const results = new Set<WallEdge>();
    const minGX = Math.floor((x - radius) / this.gridCellSize);
    const maxGX = Math.floor((x + radius) / this.gridCellSize);
    const minGY = Math.floor((y - radius) / this.gridCellSize);
    const maxGY = Math.floor((y + radius) / this.gridCellSize);

    for (let gy = minGY; gy <= maxGY; gy++) {
      for (let gx = minGX; gx <= maxGX; gx++) {
        const cell = this.spatialGrid.get(`${gx},${gy}`);
        if (cell) {
          for (const e of cell.edges) results.add(e);
        }
      }
    }
    return Array.from(results);
  }

  // 8. BVH 查询（核心 O(log n) 路径）
  private queryBVH(node: BVHNode, x: number, y: number, r: number, counter?: CollisionCounter): WallEdge[] {
    const results: WallEdge[] = [];
    const stack: BVHNode[] = [node];

    while (stack.length > 0) {
      const cur = stack.pop()!;
      if (counter) counter.n++;
      if (!this.circleAABBOverlap(x, y, r, cur.aabb)) continue;
      if (cur.edges) {
        results.push(...cur.edges);
      } else {
        if (cur.left) stack.push(cur.left);
        if (cur.right) stack.push(cur.right);
      }
    }
    return results;
  }

  private circleAABBOverlap(cx: number, cy: number, r: number, aabb: AABB): boolean {
    const closestX = Math.max(aabb.minX, Math.min(cx, aabb.maxX));
    const closestY = Math.max(aabb.minY, Math.min(cy, aabb.maxY));
    const dx = cx - closestX;
    const dy = cy - closestY;
    return dx * dx + dy * dy <= r * r;
  }

  // 9. 精确碰撞：圆 vs 线段
  private circleSegmentCollide(
    cx: number, cy: number, r: number, e: WallEdge
  ): { x: number; y: number } | null {
    const { x1, y1, x2, y2 } = e;
    const dx = x2 - x1;
    const dy = y2 - y1;
    const len2 = dx * dx + dy * dy;
    let t = len2 === 0 ? 0 : ((cx - x1) * dx + (cy - y1) * dy) / len2;
    t = Math.max(0, Math.min(1, t));

    const closestX = x1 + t * dx;
    const closestY = y1 + t * dy;

    const dcx = cx - closestX;
    const dcy = cy - closestY;
    const dist2 = dcx * dcx + dcy * dcy;

    if (dist2 >= r * r) return null;

    if (dist2 < 0.0001) {
      return { x: cx + e.nx * r, y: cy + e.ny * r };
    }

    const dist = Math.sqrt(dist2);
    const push = r - dist;
    return { x: cx + (dcx / dist) * push, y: cy + (dcy / dist) * push };
  }
}

interface GameServerOptions {
  mobCapScale?: number;
}

export class GameServer {
  private nextId = 1;
  private clients = new Map<number, ClientState>();
  private worlds: World[] = MAPS.map(() => ({ mobs: [], drops: [] }));

  // Pre-computed wall grids for each map
  private wallColliders: PolygonWallCollider[] = [];

  private tickCount = 0;
  private mobCapScale: number;

  /** 墙壁碰撞累积计时器（秒），用于 20fps 批量碰撞 */
  private wallCollisionAccumulator = 0;
  /** 墙壁碰撞间隔：20fps = 50ms */
  private readonly WALL_COLLISION_INTERVAL = 1 / 20;

  /** All active squads, keyed by their 6-character code. */
  private squads = new Map<string, Squad>();

  /**
   * Wall/circle collision tests performed during the most recently completed
   * tick. Exposed for the client's debug overlay (`collisionChecks()`); reset
   * at the start of every `tick()` so it always reflects one tick's worth of
   * work rather than accumulating forever.
   */
  private collisionCounter: CollisionCounter = { n: 0 };

  constructor(options: GameServerOptions = {}) {
    this.mobCapScale =
      Number.isFinite(options.mobCapScale) && (options.mobCapScale ?? 1) > 0
        ? options.mobCapScale ?? 1
        : 1;

    // Build polygon wall colliders with BVH for each map
    for (const map of MAPS) {
      this.wallColliders.push(new PolygonWallCollider(map.walls, map.width, map.height, 256));
    }

    for (const map of MAPS) {
      for (let i = 0; i < this.mobCapForMap(map.id); i++) this.spawnMob(map.id);
    }
  }

  playerCount() {
    let count = 0;
    for (const c of this.clients.values()) if (c.player) count++;
    return count;
  }

  /** Total entities (players + mobs + petals + drops) currently simulated across every map. */
  entityCount(): number {
    let count = 0;
    for (const c of this.clients.values()) {
      if (!c.player) continue;
      count++;
      for (const st of c.player.petals) if (st && st.alive) count++;
    }
    for (const w of this.worlds) count += w.mobs.length + w.drops.length;
    return count;
  }

  /** Wall/circle collision checks performed during the last completed tick. */
  collisionChecks(): number {
    return this.collisionCounter.n;
  }

  private mobCapForMap(mapId: number) {
    return Math.max(0, Math.round(MAPS[mapId].mobCap * this.mobCapScale));
  }

  // ---------------------------------------------------------------- clients
  addClient(id: number, send: (data: Uint8Array) => void) {
    this.clients.set(id, {
      send,
      player: null,
      events: [],
      idleSeconds: 0,
      afkPending: false,
      afkSecondsLeft: 0,
      afkLastSent: -1,
      kick: false,
      lastInDx: 0,
      lastInDy: 0,
      lastFlags: 0,
    });
  }

  /**
   * Marks the client as active, restarting the idle countdown.
   */
  private markActive(c: ClientState, canDismiss = false) {
    if (c.afkPending) {
      if (!canDismiss) return;
      c.afkPending = false;
      c.afkSecondsLeft = 0;
      c.idleSeconds = 0;
      this.sendAfkState(c);
      return;
    }
    c.idleSeconds = 0;
  }

  private sendAfkState(c: ClientState) {
    const w = new Writer(4);
    w.u8(S2C.AFK_CHECK)
      .u8(c.afkPending ? 1 : 0)
      .u16(Math.max(0, Math.ceil(c.afkSecondsLeft)));
    c.send(w.bytes());
    c.afkLastSent = c.afkPending ? Math.ceil(c.afkSecondsLeft) : -1;
  }

  private updateAfk(dt: number) {
    for (const c of this.clients.values()) {
      if (!c.player || c.kick) continue;
      if (c.afkPending) {
        c.afkSecondsLeft -= dt;
        if (c.afkSecondsLeft <= 0) {
          c.afkSecondsLeft = 0;
          c.kick = true;
          this.sendAfkState(c);
          continue;
        }
        const secs = Math.ceil(c.afkSecondsLeft);
        if (secs !== c.afkLastSent) this.sendAfkState(c);
        continue;
      }
      c.idleSeconds += dt;
      if (c.idleSeconds >= AFK_IDLE_SECONDS) {
        c.afkPending = true;
        c.afkSecondsLeft = AFK_CHECK_SECONDS;
        this.sendAfkState(c);
        this.sendChatToClient(c, `Are you still there? Click [AFK CHECK] within ${AFK_CHECK_SECONDS}s or you will be disconnected.`, "System", true, false);
      }
    }
  }


private wallCollisionBatch(dt: number, players: Player[]) {
  this.wallCollisionAccumulator += dt;
  if (this.wallCollisionAccumulator < this.WALL_COLLISION_INTERVAL) return;
  this.wallCollisionAccumulator -= this.WALL_COLLISION_INTERVAL;

  const VIEW_RADIUS = 1300;
  const VIEW_RADIUS_SQ = VIEW_RADIUS * VIEW_RADIUS;

  // ---- 玩家墙壁碰撞 ----
  for (const p of players) {
    if (!p.alive) continue;
    // 每个玩家只做自己的碰撞
    const collider = this.wallColliders[p.mapId];
    [p.x, p.y] = collider.collideCircle(p.x, p.y, PLAYER_RADIUS, this.collisionCounter);
  }

  // ---- Mob 墙壁碰撞 ----
  for (let m = 0; m < MAPS.length; m++) {
    const map = MAPS[m];
    const collider = this.wallColliders[m];
    // 收集该地图的玩家位置
    const mapPlayers = players.filter(p => p.mapId === m && p.alive);
    const playerPositions = mapPlayers.map(p => ({ x: p.x, y: p.y }));

    for (const mob of this.worlds[m].mobs) {
      // 检查是否在玩家视野内
      let inView = false;
      if (mob.ownerId !== 0) {
        inView = true; // 召唤物始终在视野内
      } else {
        for (const pos of playerPositions) {
          const dx = mob.x - pos.x;
          const dy = mob.y - pos.y;
          if (dx * dx + dy * dy < VIEW_RADIUS_SQ) {
            inView = true;
            break;
          }
        }
      }

      // 不在视野内，跳过墙壁碰撞
      if (!inView) continue;

      [mob.x, mob.y] = collider.collideCircle(mob.x, mob.y, mob.radius, this.collisionCounter);
    }
  }
}

  drainKicks(): number[] {
    const ids: number[] = [];
    for (const [id, c] of this.clients) {
      if (c.kick) {
        c.kick = false;
        ids.push(id);
      }
    }
    return ids;
  }

  isAfkPending(id: number): boolean {
    return this.clients.get(id)?.afkPending ?? false;
  }

  removeClient(id: number) {
    const c = this.clients.get(id);
    if (c?.player) {
      const w = this.worlds[c.player.mapId];
      w.mobs = w.mobs.filter((m) => m.ownerId !== c.player!.id);
      if (c.player.squadCode) {
        this.removePlayerFromSquad(c.player);
      }
    }
    this.clients.delete(id);
  }

  getSave(id: number): PlayerSave | null {
    const p = this.clients.get(id)?.player;
    if (!p) return null;
    return {
      slots: p.slots,
      secondary: p.secondary,
      bag: p.bag,
      xp: p.xp,
      mapId: p.mapId,
      nextOracleAt: p.nextOracleAt,
      nextTradeAt: p.nextTradeAt,
    };
  }

  // ------------------------------------------------------------- networking
  handleMessage(clientId: number, data: Uint8Array) {
    const c = this.clients.get(clientId);
    if (!c) return;
    const r = new Reader(data);
    const type = r.u8();
    if (type !== C2S.INPUT && type !== C2S.PING && type !== C2S.BONUS_STATUS) {
      this.markActive(c, type === C2S.AFK_ACK);
    }

    switch (type) {
      case C2S.JOIN: {
        const name = r.str().slice(0, 14) || "flower";
        const mapId = clamp(r.u8(), 0, MAPS.length - 1);
        const xp = r.u32();
        const p = new Player(this.nextId++);
        p.name = name;
        p.mapId = mapId;
        p.xp = xp;
        for (let i = 0; i < SLOT_COUNT; i++) p.slots[i] = readCell(r);
        for (let i = 0; i < SECONDARY_SLOT_COUNT; i++) p.secondary[i] = readCell(r);
        const bagCount = Math.min(r.u16(), BAG_MAX);
        if (p.bag.length < bagCount) p.bag.length = bagCount;
        for (let i = 0; i < bagCount; i++) p.bag[i] = readCell(r);
        for (let i = 0; i < p.bag.length; i++) if (p.bag[i] === undefined) p.bag[i] = null;
        const oracleSecLeft = r.u32();
        const tradeSecLeft = r.u32();
        const now = Date.now();
        p.nextOracleAt = oracleSecLeft > 0 ? now + oracleSecLeft * 1000 : 0;
        p.nextTradeAt = tradeSecLeft > 0 ? now + tradeSecLeft * 1000 : 0;
        this.setBonusStatus(p, r.remaining >= 3 ? r.u8() : 1, r.remaining >= 2 ? r.u16() : 0);
        if (!p.slots.some(Boolean) && !p.secondary.some(Boolean) && !p.bag.some(Boolean)) {
          p.slots[0] = { item: 0, rarity: 0, count: 1 };
          p.slots[1] = { item: 0, rarity: 0, count: 1 };
          p.slots[2] = { item: 1, rarity: 0, count: 1 };
          p.slots[3] = { item: 0, rarity: 0, count: 1 };
          p.secondary[0] = { item: 2, rarity: 0, count: 1 };
          p.secondary[1] = { item: 8, rarity: 0, count: 1 };
        }
        c.player = p;
        this.applyLevel(p);
        this.rebuildPetals(p);
        this.spawnPlayer(p);
        this.sendWelcome(c, p);
        break;
      }

      case C2S.INPUT: {
        const p = c.player;
        if (!p) return;
        p.inDx = r.i8() / 100;
        p.inDy = r.i8() / 100;
        p.flags = r.u8();
        if (p.inDx !== c.lastInDx || p.inDy !== c.lastInDy || p.flags !== c.lastFlags) {
          c.lastInDx = p.inDx;
          c.lastInDy = p.inDy;
          c.lastFlags = p.flags;
          this.markActive(c);
        }
        break;
      }

      case C2S.AFK_ACK: {
        break;
      }

      case C2S.BONUS_STATUS: {
        const p = c.player;
        if (!p || r.remaining < 3) return;
        this.setBonusStatus(p, r.u8(), r.u16());
        break;
      }

      case C2S.SWAP: {
        const p = c.player;
        if (!p) return;
        const from = r.u16();
        const to = r.u16();
        if (isBagCell(from)) this.moveOneFromBag(p, from, to);
        else this.swapCells(p, from, to);
        break;
      }

      case C2S.SWAP_ROW: {
        const p = c.player;
        if (!p) return;
        const which = r.u8();
        if (which === SWAP_ROW_ALL) this.swapAllRows(p);
        else this.swapRowSlot(p, which);
        break;
      }

      case C2S.CRAFT: {
        const p = c.player;
        if (!p) return;
        this.craft(c, p, r.u8(), r.u8(), r.u16() || CRAFT_CARD_COUNT);
        break;
      }

      case C2S.ORACLE: {
        const p = c.player;
        if (!p) return;
        this.oracle(c, p, r.u8(), r.u8());
        break;
      }

      case C2S.TRADE: {
        const p = c.player;
        if (!p) return;
        this.trade(c, p, r.u8(), r.u8(), r.u16());
        break;
      }

      case C2S.CHANGE_MAP: {
        const p = c.player;
        if (!p) return;
        const mapId = clamp(r.u8(), 0, MAPS.length - 1);
        if (mapId === p.mapId) return;
        const oldWorld = this.worlds[p.mapId];
        oldWorld.mobs = oldWorld.mobs.filter((m) => m.ownerId !== p.id);
        p.mapId = mapId;
        this.spawnPlayer(p);
        this.rebuildPetals(p);
        this.sendWelcome(c, p);
        break;
      }

      case C2S.RESPAWN: {
        const p = c.player;
        if (!p || p.alive) return;
        p.alive = true;
        this.applyLevel(p);
        p.hp = p.maxHp;
        p.shield = 0;
        this.spawnPlayer(p);
        this.rebuildPetals(p);
        p.statsDirty = true;
        break;
      }

      case C2S.PING: {
        const stamp = r.u32();
        const w = new Writer(8);
        w.u8(S2C.PONG).u32(stamp);
        c.send(w.bytes());
        break;
      }

      case C2S.CHAT: {
        const p = c.player;
        if (!p) return;
        const msg = r.str();
        this.handleChat(c, p, msg);
        break;
      }
    }
  }

  // ---------------------------------------------------------------- squad helpers
  private generateSquadCode(): string {
    const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
    let code = "";
    for (let i = 0; i < SQUAD_CODE_LENGTH; i++) {
      code += chars[Math.floor(Math.random() * chars.length)];
    }
    return code;
  }

  private sendChatToClient(c: ClientState, text: string, sender: string, isSystem: boolean, isCraftReport: boolean) {
    const w = new Writer(256);
    w.u8(S2C.CHAT);
    w.str(text.slice(0, 200));
    w.str(sender.slice(0, 30));
    w.u8(isSystem ? 1 : 0);
    w.u8(isCraftReport ? 1 : 0);
    c.send(w.bytes());
  }

  private broadcastChatToSquad(squadCode: string, text: string, sender: string) {
    const squad = this.squads.get(squadCode);
    if (!squad) return;
    for (const member of squad.members.values()) {
      const c = this.clients.get(member.clientId);
      if (c) this.sendChatToClient(c, text, sender, false, false);
    }
  }

  private broadcastChatToMap(mapId: number, text: string, sender: string) {
    for (const c of this.clients.values()) {
      if (c.player && c.player.mapId === mapId) {
        this.sendChatToClient(c, text, sender, false, false);
      }
    }
  }

  private sendSquadUpdate(c: ClientState, squadCode: string) {
    const w = new Writer(16);
    w.u8(S2C.SQUAD_UPDATE);
    w.str(squadCode.slice(0, SQUAD_CODE_LENGTH));
    c.send(w.bytes());
  }

  private removePlayerFromSquad(p: Player): string | null {
    if (!p.squadCode) return null;
    const squad = this.squads.get(p.squadCode);
    if (!squad) { p.squadCode = ""; return null; }
    squad.members.delete(p.id);
    const oldCode = p.squadCode;
    p.squadCode = "";
    if (squad.members.size === 0) this.squads.delete(oldCode);
    return oldCode;
  }

  private canJoinSquad(p: Player, squad: Squad): string | null {
    if (squad.members.size >= SQUAD_MAX_MEMBERS) return "Squad is full.";
    for (const member of squad.members.values()) {
      if (Math.abs(p.level - member.level) > SQUAD_LEVEL_GAP_MAX) {
        return `Level gap too large (max ${SQUAD_LEVEL_GAP_MAX}).`;
      }
    }
    return null;
  }

  // ---------------------------------------------------------------- chat & commands
  private handleChat(c: ClientState, p: Player, msg: string) {
    const trimmed = msg.trim();
    if (!trimmed) return;
    if (trimmed.startsWith("/")) { this.handleCommand(c, p, trimmed); return; }
    this.broadcastChatToMap(p.mapId, trimmed, p.name);
  }

  private handleCommand(c: ClientState, p: Player, cmd: string) {
    const parts = cmd.split(/\s+/);
    const command = parts[0].toLowerCase();
    switch (command) {
      case "/claim":
        this.sendChatToClient(c, "Daily bonus can be claimed from the main menu.", "System", true, false);
        break;
      case "/create_public_squad":
      case "/create_private_squad": {
        if (p.squadCode) { this.sendChatToClient(c, "Already in a squad. Use /leave_squad first.", "System", true, false); return; }
        const key = this.generateSquadCode();
        const sq: Squad = { code: key, isPublic: command === "/create_public_squad", members: new Map(), createdAt: Date.now() };
        sq.members.set(p.id, { clientId: this.getClientIdForPlayer(p), playerId: p.id, name: p.name, level: p.level });
        this.squads.set(key, sq);
        p.squadCode = key;
        this.sendChatToClient(c, `${command === "/create_public_squad" ? "Public" : "Private"} squad created! Code: ${key}`, "System", true, false);
        this.sendSquadUpdate(c, key);
        break;
      }
      case "/join_squad": {
        const code = (parts[1] || "").toUpperCase();
        if (!code) { this.sendChatToClient(c, "Usage: /join_squad <CODE>", "System", true, false); return; }
        if (p.squadCode) { this.sendChatToClient(c, "Already in a squad.", "System", true, false); return; }
        const sq = this.squads.get(code);
        if (!sq) { this.sendChatToClient(c, "Squad not found.", "System", true, false); return; }
        const err = this.canJoinSquad(p, sq);
        if (err) { this.sendChatToClient(c, err, "System", true, false); return; }
        sq.members.set(p.id, { clientId: this.getClientIdForPlayer(p), playerId: p.id, name: p.name, level: p.level });
        p.squadCode = code;
        this.sendChatToClient(c, `Joined squad! Code: ${code} (${sq.members.size} members)`, "System", true, false);
        this.sendSquadUpdate(c, code);
        this.broadcastChatToSquad(code, `System: ${p.name} joined the squad.`, "System");
        break;
      }
      case "/leave_squad": {
        if (!p.squadCode) { this.sendChatToClient(c, "Not in a squad.", "System", true, false); return; }
        const old = p.squadCode;
        const sq = this.squads.get(old);
        this.removePlayerFromSquad(p);
        this.sendChatToClient(c, "Left the squad.", "System", true, false);
        this.sendSquadUpdate(c, "");
        if (sq && sq.members.size > 0) this.broadcastChatToSquad(old, `System: ${p.name} left.`, "System");
        break;
      }
      case "/find_public_squad": {
        if (p.squadCode) { this.sendChatToClient(c, "Already in a squad.", "System", true, false); return; }
        const candidates: Squad[] = [];
        for (const sq of this.squads.values()) {
          if (!sq.isPublic || sq.members.size >= SQUAD_MAX_MEMBERS) continue;
          if (!this.canJoinSquad(p, sq)) candidates.push(sq);
        }
        if (!candidates.length) { this.sendChatToClient(c, "No available public squads found.", "System", true, false); return; }
        const chosen = candidates[Math.floor(Math.random() * candidates.length)];
        chosen.members.set(p.id, { clientId: this.getClientIdForPlayer(p), playerId: p.id, name: p.name, level: p.level });
        p.squadCode = chosen.code;
        this.sendChatToClient(c, `Auto-joined public squad! Code: ${chosen.code} (${chosen.members.size} members)`, "System", true, false);
        this.sendSquadUpdate(c, chosen.code);
        this.broadcastChatToSquad(chosen.code, `System: ${p.name} joined.`, "System");
        break;
      }
      case "/help": {
        const commands = [
          "/claim — Daily bonus from main menu",
          "/create_public_squad — Create a public squad",
          "/create_private_squad — Create a private squad",
          "/join_squad <CODE> — Join a squad by code",
          "/leave_squad — Leave current squad",
          "/find_public_squad — Auto-join a public squad",
          "/find_player — Show player count per map",
          "/help — Show this help message",
        ];
        for (const line of commands) {
          this.sendChatToClient(c, line, "System", true, false);
        }
        break;
      }
      case "/find_player": {
        const mapCounts = new Map<number, number>();
        for (const client of this.clients.values()) {
          if (client.player) {
            mapCounts.set(client.player.mapId, (mapCounts.get(client.player.mapId) || 0) + 1);
          }
        }
        let total = 0;
        for (const map of MAPS) {
          const count = mapCounts.get(map.id) || 0;
          total += count;
          this.sendChatToClient(c, `${map.name}: ${count} player${count === 1 ? "" : "s"}`, "System", true, false);
        }
        this.sendChatToClient(c, `Total: ${total} player${total === 1 ? "" : "s"}`, "System", true, false);
        break;
      }
      default:
        this.sendChatToClient(c, `Unknown command: ${command}`, "System", true, false);
    }
  }

  private getClientIdForPlayer(p: Player): number {
    for (const [id, c] of this.clients.entries()) { if (c.player === p) return id; }
    return 0;
  }

  private sendWelcome(c: ClientState, p: Player) {
    const map = MAPS[p.mapId];
    const w = new Writer(64 + map.walls.length * 8);
    w.u8(S2C.WELCOME).u16(p.id).u8(p.mapId).u16(map.width).u16(map.height);
    w.u16(map.walls.length);
    for (const wall of map.walls) w.u16(wall.x).u16(wall.y).u16(wall.w).u16(wall.h);
    c.send(w.bytes());
    p.dirty = true;
    p.statsDirty = true;
  }

  private pushEvent(c: ClientState, kind: number, x: number, y: number, value: number, item = EMPTY_ITEM, rarity = 0) {
    const w = new Writer(16);
    w.u8(S2C.EVENT).u8(kind).i16(Math.round(x)).i16(Math.round(y)).u32(Math.max(0, Math.round(value))).u8(item).u8(rarity);
    c.events.push(w.bytes());
  }

  private clientOf(playerId: number): ClientState | null {
    for (const c of this.clients.values()) if (c.player && c.player.id === playerId) return c;
    return null;
  }

  // ------------------------------------------------------------- inventory
  private cellAt(p: Player, idx: number): Cell | null {
    if (isMainCell(idx)) return p.slots[idx] ?? null;
    if (idx < HOTBAR_CELLS) return p.secondary[idx - SLOT_COUNT] ?? null;
    return p.bag[idx - HOTBAR_CELLS] ?? null;
  }

  private setCell(p: Player, idx: number, cell: Cell | null) {
    if (isMainCell(idx)) { p.slots[idx] = cell; return; }
    if (idx < HOTBAR_CELLS) { p.secondary[idx - SLOT_COUNT] = cell; return; }
    const bagIdx = idx - HOTBAR_CELLS;
    while (p.bag.length <= bagIdx) p.bag.push(null);
    p.bag[bagIdx] = cell;
  }

  private swapCells(p: Player, a: number, b: number) {
    if (a === b || a >= TOTAL_CELLS || b >= TOTAL_CELLS) return;
    const ca = this.cellAt(p, a);
    const cb = this.cellAt(p, b);
    if (ca && cb && ca.item === cb.item && ca.rarity === cb.rarity) {
      cb.count += ca.count;
      this.setCell(p, a, null);
    } else {
      this.setCell(p, a, cb);
      this.setCell(p, b, ca);
    }
    if (isMainCell(a) || isMainCell(b)) this.rebuildPetals(p);
    p.dirty = true;
  }

  private swapRowSlot(p: Player, slot: number) {
    if (slot < 0 || slot >= Math.min(SLOT_COUNT, SECONDARY_SLOT_COUNT)) return;
    const main = p.slots[slot] ?? null;
    const backup = p.secondary[slot] ?? null;
    if (!main && !backup) return;
    p.slots[slot] = backup;
    p.secondary[slot] = main;
    this.rebuildPetals(p);
    this.startReload(p, slot);
    p.dirty = true;
  }

  private swapAllRows(p: Player) {
    const n = Math.min(SLOT_COUNT, SECONDARY_SLOT_COUNT);
    let touched = false;
    for (let i = 0; i < n; i++) {
      const m = p.slots[i] ?? null;
      const b = p.secondary[i] ?? null;
      if (!m && !b) continue;
      p.slots[i] = b;
      p.secondary[i] = m;
      touched = true;
    }
    if (!touched) return;
    this.rebuildPetals(p);
    for (let i = 0; i < n; i++) this.startReload(p, i);
    p.dirty = true;
  }

  private startReload(p: Player, slot: number) {
    const cell = p.slots[slot];
    const st = p.petals[slot];
    if (!cell || !st) return;
    const def = ITEMS[cell.item];
    if (!def || !orbitsAsPetal(def.kind)) return;
    st.alive = false;
    st.timer = def.reload > 0 ? def.reload : 0.001;
  }

  private moveOneFromBag(p: Player, from: number, to: number) {
    if (from === to || !isBagCell(from) || to >= TOTAL_CELLS) return;
    const source = this.cellAt(p, from);
    if (!source || source.count <= 0) return;
    const one: Cell = { item: source.item, rarity: source.rarity, count: 1 };
    const target = this.cellAt(p, to);
    if (isHotbarCell(to)) {
      if (target && !this.addItem(p, target.item, target.rarity, target.count)) return;
      this.setCell(p, to, one);
      if (isMainCell(to)) this.rebuildPetals(p);
    } else {
      if (target && (target.item !== one.item || target.rarity !== one.rarity || target.count >= 999)) return;
      if (target) target.count += 1;
      else this.setCell(p, to, one);
    }
    source.count -= 1;
    if (source.count === 0) this.setCell(p, from, null);
    p.dirty = true;
  }

  addItem(p: Player, item: number, rarity: number, count = 1): boolean {
    if (count <= 0) return true;
    let left = count;
    for (const cell of p.bag) {
      if (left <= 0) break;
      if (cell && cell.item === item && cell.rarity === rarity && cell.count < 999) {
        const room = 999 - cell.count;
        const put = Math.min(room, left);
        cell.count += put;
        left -= put;
      }
    }
    while (left > 0) {
      let idx = p.bag.indexOf(null);
      if (idx < 0) {
        if (p.bag.length >= BAG_MAX) { p.dirty = true; return false; }
        idx = p.bag.length;
        p.bag.push(null);
      }
      const put = Math.min(999, left);
      p.bag[idx] = { item, rarity, count: put };
      left -= put;
    }
    p.dirty = true;
    return true;
  }

  private takeFromBag(p: Player, item: number, rarity: number, count: number): number {
    let need = count;
    for (let i = 0; i < p.bag.length && need > 0; i++) {
      const cell = p.bag[i];
      if (!cell || cell.item !== item || cell.rarity !== rarity) continue;
      const take = Math.min(need, cell.count);
      cell.count -= take;
      need -= take;
      if (cell.count <= 0) p.bag[i] = null;
    }
    return count - need;
  }

  private countOf(p: Player, item: number, rarity: number): number {
    let have = 0;
    for (const cell of p.bag) if (cell && cell.item === item && cell.rarity === rarity) have += cell.count;
    return have;
  }

  private craft(c: ClientState, p: Player, item: number, rarity: number, totalCards: number) {
    if (item >= ITEMS.length || ITEMS[item].kind === "trinket") return;
    const successRate = craftChanceFor(rarity);
    if (rarity >= MAX_CRAFT_RARITY || successRate === undefined) return;
    const needed = Math.max(1, totalCards);
    if (this.countOf(p, item, rarity) < needed) return;
    const used = this.takeFromBag(p, item, rarity, needed);
    if (used !== needed) return;
    const attempts = Math.max(1, Math.floor(needed / CRAFT_CARDS_PER_ATTEMPT));
    let successes = 0;
    for (let i = 0; i < attempts; i++) { if (Math.random() < successRate) successes++; }
    if (successes > 0) {
      this.addItem(p, item, rarity + 1, successes);
      this.pushEvent(c, EVT.CRAFT_OK, p.x, p.y, successes, item, rarity + 1);
    } else {
      const kept = 1 + Math.floor(Math.random() * Math.min(4, needed));
      this.addItem(p, item, rarity, kept);
      this.pushEvent(c, EVT.CRAFT_FAIL, p.x, p.y, needed - kept, item, rarity);
    }
    p.dirty = true;
  }

  private oracle(c: ClientState, p: Player, item: number, rarity: number) {
    if (item >= ITEMS.length || ITEMS[item].kind === "trinket") return;
    const required = oracleRequiredCount(rarity);
    if (required === undefined || Date.now() < p.nextOracleAt) return;
    const have = this.countOf(p, item, rarity);
    if (have < required) return;
    this.takeFromBag(p, item, rarity, required);
    const targetRarity = rarity + ORACLE_SKIP;
    this.addItem(p, item, targetRarity, 1);
    p.nextOracleAt = Date.now() + ORACLE_COOLDOWN_HOURS * 3600 * 1000;
    this.pushEvent(c, EVT.ORACLE_OK, p.x, p.y, 0, item, targetRarity);
    p.dirty = true;
    p.statsDirty = true;
  }

  private trade(c: ClientState, p: Player, item: number, rarity: number, requestedCount: number) {
    if (item >= ITEMS.length || ITEMS[item].kind === "trinket" || Date.now() < p.nextTradeAt) return;
    const have = this.countOf(p, item, rarity);
    const want = requestedCount > 0 ? Math.min(requestedCount, have) : have;
    if (want <= 0) return;
    const used = this.takeFromBag(p, item, rarity, want);
    if (used <= 0) return;
    this.addItem(p, TRINKET_ITEM, rarity, used);
    p.nextTradeAt = Date.now() + TRADE_COOLDOWN_HOURS * 3600 * 1000;
    this.pushEvent(c, EVT.TRADE_OK, p.x, p.y, used, TRINKET_ITEM, rarity);
    p.dirty = true;
    p.statsDirty = true;
  }

  // --------------------------------------------------------------- spawning
  private spawnPlayer(p: Player) {
    const map = MAPS[p.mapId];
    const collider = this.wallColliders[p.mapId];
    const spawnTiles = findSpawnTiles(p.mapId);
    if (spawnTiles.length > 0) {
      const tile = spawnTiles[Math.floor(Math.random() * spawnTiles.length)];
      const tileW = map.width / BLOCK_GRID_COLS;
      const tileH = map.height / BLOCK_GRID_ROWS;
      for (let tries = 0; tries < 20; tries++) {
        const x = tile.col * tileW + Math.random() * tileW;
        const y = tile.row * tileH + Math.random() * tileH;
        const [cx, cy] = collider.collideCircle(x, y, 40);
        if (Math.abs(cx - x) < 0.01 && Math.abs(cy - y) < 0.01) {
          p.x = x; p.y = y; p.hp = p.maxHp; p.alive = true; p.statsDirty = true;
          return;
        }
      }
    }
    for (let tries = 0; tries < 60; tries++) {
      const x = 200 + Math.random() * (map.width - 400);
      const y = 200 + Math.random() * (map.height - 400);
      const [cx, cy] = collider.collideCircle(x, y, 40);
      if (Math.abs(cx - x) < 0.01 && Math.abs(cy - y) < 0.01) { p.x = x; p.y = y; break; }
      p.x = x; p.y = y;
    }
    p.hp = p.maxHp; p.alive = true; p.statsDirty = true;
  }

  private spawnMob(mapId: number) {
    const map = MAPS[mapId];
    const collider = this.wallColliders[mapId];
    const type = map.mobs[(Math.random() * map.mobs.length) | 0];
    let rarity = 0, x = 0, y = 0, placed = false;
    for (let tries = 0; tries < 80; tries++) {
      x = 200 + Math.random() * (map.width - 400);
      y = 200 + Math.random() * (map.height - 400);
      const zone = getBlockAt(mapId, x, y);
      if (zone < "A" || zone > "G") continue;
      const cr = rollZoneRarity(zone);
      const crRadius = MOBS[type].radius * mobSizeMult(cr);
      const [cx, cy] = collider.collideCircle(x, y, crRadius + 6);
      if (Math.abs(cx - x) >= 0.01 || Math.abs(cy - y) >= 0.01) continue;
      rarity = cr; placed = true; break;
    }
    if (!placed) return;
    this.worlds[mapId].mobs.push(new Mob(this.nextId++, type, mapId, x, y, rarity));
  }

  private healthBonusOf(p: Player): number {
    let bonus = 0;
    for (let i = 0; i < SLOT_COUNT; i++) {
      const cell = p.slots[i];
      if (!cell) continue;
      const def = ITEMS[cell.item];
      if (def?.healthBonus) bonus += def.healthBonus * rarityMult(cell.rarity);
    }
    return bonus;
  }

  private applyLevel(p: Player) {
    const lvl = levelFromXp(p.xp);
    const maxHp = Math.round(110 + lvl * 16 + this.healthBonusOf(p));
    if (maxHp !== p.maxHp) {
      const ratio = p.hp / p.maxHp;
      p.maxHp = maxHp;
      p.hp = Math.min(maxHp, Math.max(1, ratio * maxHp));
      if (p.shield > maxHp) p.shield = maxHp;
      p.statsDirty = true;
    }
    if (lvl !== p.level) { p.level = lvl; p.statsDirty = true; }
  }

  private despawnPets(p: Player, slot: number) {
    const pets = p.pets[slot] || [];
    for (const pet of pets) {
      const w = this.worlds[pet.mapId];
      if (w) w.mobs = w.mobs.filter((m) => m !== pet);
    }
    p.pets[slot] = [];
  }

  private rebuildPetals(p: Player) {
    const petals: PetalState[] = [];
    for (let i = 0; i < SLOT_COUNT; i++) {
      const old = p.petals[i];
      const cell = p.slots[i];
      const def = cell ? ITEMS[cell.item] : null;
      const orbits = !!def && orbitsAsPetal(def.kind);
      const maxHp = orbits ? def!.health * rarityMult(cell!.rarity) : 1;
      petals.push({
        id: old?.id ?? this.nextId++, alive: orbits, hp: maxHp, maxHp, timer: 0,
        x: p.x, y: p.y, hitCd: 0,
        specialTimer: cell && isAbsorbItem(cell.item) ? ROSE_HEAL_DELAY : 0, absorbTimer: 0,
      });
      const pets = p.pets[i] || [];
      const sameSummon = !!cell && !!def && def.kind === "summon" &&
        pets.every((pet) => pet.type === def.petMob && pet.sourceItem === cell.item && pet.sourceRarity === cell.rarity);
      if (pets.length > 0 && !sameSummon) this.despawnPets(p, i);
    }
    p.petals = petals;
  }

  // ------------------------------------------------------------------ tick
  tick(dt: number) {
    this.tickCount++;
    this.collisionCounter = { n: 0 };
    this.updateAfk(dt);
    const players: Player[] = [];
    for (const c of this.clients.values()) if (c.player) players.push(c.player);
    for (const p of players) this.updatePlayer(p, dt, players);
    for (let m = 0; m < MAPS.length; m++) this.updateWorld(m, dt, players);
    // 玩家墙壁碰撞已移至 wallCollisionBatch() 以 20fps 批量处理
    for (const p of players) this.updatePetals(p, dt);
    for (const p of players) this.pickupDrops(p);
    // ⭐ 20fps 批量墙壁碰撞（所有实体统一处理，降低 CPU 占用）
    this.wallCollisionBatch(dt, players);
    for (const c of this.clients.values()) this.sendState(c);
  }

  private updatePlayer(p: Player, dt: number, players: Player[]) {
    if (!p.alive) return;
    const map = MAPS[p.mapId];
    const collider = this.wallColliders[p.mapId];
    let speedBonus = 0;
    for (let i = 0; i < SLOT_COUNT; i++) {
      const cell = p.slots[i];
      if (!cell) continue;
      const def = ITEMS[cell.item];
      const alive = orbitsAsPetal(def.kind) ? p.petals[i]?.alive : true;
      if (!alive) continue;
      if (def.speed) speedBonus += def.speed * (1 + cell.rarity * 0.12);
    }
    const speed = (190 + p.level * 0.8) * (1 + speedBonus / 100);
    const mag = Math.hypot(p.inDx, p.inDy);
    const nx = mag > 1 ? p.inDx / mag : p.inDx;
    const ny = mag > 1 ? p.inDy / mag : p.inDy;
    p.vx += (nx * speed - p.vx) * Math.min(1, dt * 9);
    p.vy += (ny * speed - p.vy) * Math.min(1, dt * 9);
    [p.x, p.y] = collider.moveCircle(p.x, p.y, p.vx * dt, p.vy * dt, PLAYER_RADIUS, this.collisionCounter);
    p.x = clamp(p.x, PLAYER_RADIUS, map.width - PLAYER_RADIUS);
    p.y = clamp(p.y, PLAYER_RADIUS, map.height - PLAYER_RADIUS);
    for (const o of players) {
      if (o === p || o.mapId !== p.mapId || !o.alive) continue;
      this.collisionCounter.n++;
      const dx = p.x - o.x;
      const dy = p.y - o.y;
      const d = Math.hypot(dx, dy);
      if (d < PLAYER_RADIUS * 2 && d > 0.001) {
        const push = (PLAYER_RADIUS * 2 - d) * 0.5;
        p.x += (dx / d) * push;
        p.y += (dy / d) * push;
      }
    }
    p.x = clamp(p.x, PLAYER_RADIUS, map.width - PLAYER_RADIUS);
    p.y = clamp(p.y, PLAYER_RADIUS, map.height - PLAYER_RADIUS);
    p.hurtCd = Math.max(0, p.hurtCd - dt);
    const attack = (p.flags & 1) !== 0;
    const defend = (p.flags & 2) !== 0;

    // Bubble: trigger on rising edge of defend (Shift/Contract key)
    if (defend && !p.wasDefending) {
      this.breakBubbles(p);
    }
    p.wasDefending = defend;

    // Third Eye petals expand the orbit range. The bonus is added to the base
    // target so the smooth interpolation still works with spread/defend modes.
    const eyeBonus = thirdEyeOrbitBonus(p.slots);
    const targetOrbit = (attack ? 118 : defend ? 34 : 62) + eyeBonus;
    p.orbit += (targetOrbit - p.orbit) * Math.min(1, dt * 6);
    p.baseAngle += dt * (attack ? 3.4 : 2.2);
    this.applyLevel(p);
  }

  /**
   * Break all active Bubble petals when the player presses Defend (Shift/Contract).
   * Each bubble applies a rarity-scaled push force away from the player.
   */
  private breakBubbles(p: Player) {
    for (let i = 0; i < SLOT_COUNT; i++) {
      const cell = p.slots[i];
      if (!cell) continue;
      const def = ITEMS[cell.item];
      if (!def || def.name !== "Bubble") continue;
      const st = p.petals[i];
      if (!st || !st.alive) continue;

      // Calculate push force based on rarity (mirrors rarityMult scaling)
      const mult = rarityMult(cell.rarity);
      const basePush = 800;
      const pushForce = basePush * Math.min(4.0, mult);

      const dx = p.x - st.x;
      const dy = p.y - st.y;
      const dist = Math.hypot(dx, dy);

      let vx: number;
      let vy: number;
      if (dist > 0.01) {
        vx = (dx / dist) * pushForce;
        vy = (dy / dist) * pushForce;
      } else {
        const angle = Math.random() * Math.PI * 2;
        vx = Math.cos(angle) * pushForce;
        vy = Math.sin(angle) * pushForce;
      }

      // Apply impulse to player velocity
      p.vx += vx;
      p.vy += vy;

      // Also apply the push to any alive Moon petal. Petals have no velocity
      // field (they interpolate toward their orbit target), so we apply the
      // push as a position displacement; the orbit interpolation will spring
      // the Moon back toward its orbit over the next few frames, producing a
      // visible "knocked away then returns" effect.
      for (let j = 0; j < SLOT_COUNT; j++) {
        if (j === i) continue;
        const mcell = p.slots[j];
        if (!mcell) continue;
        const mdef = ITEMS[mcell.item];
        if (!mdef || !(mdef.name ?? "").toLowerCase().includes("moon")) continue;
        const mst = p.petals[j];
        if (!mst || !mst.alive) continue;
        mst.x += vx * 0.1;
        mst.y += vy * 0.1;
      }

      // Break the bubble: kill petal and start reload
      st.alive = false;
      st.hp = 0;
      st.timer = def.reload > 0 ? def.reload : 0.001;
    }
  }

  private updatePetals(p: Player, dt: number) {
    if (!p.alive) return;
    const world = this.worlds[p.mapId];
    let liveCount = 0;
    for (let i = 0; i < SLOT_COUNT; i++) {
      const cell = p.slots[i];
      if (!cell) continue;
      if (orbitsAsPetal(ITEMS[cell.item].kind)) liveCount++;
    }

    // -----------------------------------------------------------------
    // Moon orbit center: if the player has a Moon petal, every other
    // petal orbits around the Moon instead of around the player body.
    // The Moon itself still orbits the player. We snapshot the Moon's
    // current position here (1-frame lag, imperceptible) so the order
    // in which petals are processed does not matter.
    // -----------------------------------------------------------------
    let moonSt: PetalState | null = null;
    for (let i = 0; i < SLOT_COUNT; i++) {
      const cell = p.slots[i];
      if (!cell) continue;
      const def = ITEMS[cell.item];
      if ((def.name ?? "").toLowerCase().includes("moon")) {
        moonSt = p.petals[i];
        break;
      }
    }
    const moonAlive = !!moonSt && moonSt.alive;
    const orbitCenterX = moonAlive ? moonSt!.x : p.x;
    const orbitCenterY = moonAlive ? moonSt!.y : p.y;

    let index = 0;
    for (let i = 0; i < SLOT_COUNT; i++) {
      const cell = p.slots[i];
      const st = p.petals[i];
      if (!cell || !st) continue;
      const def = ITEMS[cell.item];
      const isSummon = def.kind === "summon";
      if (!orbitsAsPetal(def.kind)) continue;
      if (isSummon) this.cleanupPets(p, i);
      const slotAngle = p.baseAngle + (index / Math.max(1, liveCount)) * Math.PI * 2;
      index++;
      st.hitCd = Math.max(0, st.hitCd - dt);
      if (!st.alive) {
        st.timer -= dt;
        if (st.timer <= 0) {
          st.alive = true;
          st.maxHp = def.health * rarityMult(cell.rarity);
          st.hp = st.maxHp;
          st.specialTimer = isAbsorbItem(cell.item) ? ROSE_HEAL_DELAY : 0;
          st.absorbTimer = 0;
        }
        continue;
      }
      if (isSummon && (p.pets[i]?.length ?? 0) < getSummonCount(cell.item)) {
        this.hatchPet(p, i, cell);
        st.alive = false; st.hp = 0; st.timer = def.reload;
        continue;
      }
      const absorbs = isAbsorbItem(cell.item) && (!!def.heal || !!def.shield);
      // Magnets and summons (eggs) stay close like Rose/Shell — they never
      // spread out no matter the spread flag, so their visual radius stays
      // tight while other petals still fan out on attack.
      const staysTight = isSummon || (def.name ?? "").toLowerCase().includes("magnet") || (def.name ?? "").toLowerCase().includes("bubble");
      const orbitRadius = (absorbs || staysTight) ? Math.min(p.orbit, 62) : p.orbit;
      // Moon orbits the player; every other petal orbits the Moon (if alive).
      const isMoon = (def.name ?? "").toLowerCase().includes("moon");
      const cx = isMoon ? p.x : orbitCenterX;
      const cy = isMoon ? p.y : orbitCenterY;
      const tx = cx + Math.cos(slotAngle) * orbitRadius;
      const ty = cy + Math.sin(slotAngle) * orbitRadius;
      if (absorbs) {
        const missing = def.heal ? Math.max(0, p.maxHp - p.hp) : Math.max(0, p.maxHp - p.shield);
        st.specialTimer = Math.max(0, st.specialTimer - dt);
        if (st.absorbTimer > 0) {
          const travelStep = Math.min(1, dt / Math.max(dt, st.absorbTimer));
          st.x += (p.x - st.x) * travelStep;
          st.y += (p.y - st.y) * travelStep;
          st.absorbTimer = Math.max(0, st.absorbTimer - dt);
          if (st.absorbTimer <= 0 && missing > 0) {
            const amount = Math.min(missing, (def.heal ?? def.shield ?? 0) * rarityMult(cell.rarity));
            if (def.heal) p.hp += amount; else p.shield += amount;
            p.statsDirty = true;
            const owner = this.clientOf(p.id);
            if (owner) this.pushEvent(owner, EVT.HEAL, p.x, p.y, Math.round(amount), cell.item, cell.rarity);
            st.alive = false; st.hp = 0; st.timer = def.reload;
          }
          continue;
        }
        st.x += (tx - st.x) * Math.min(1, dt * 14);
        st.y += (ty - st.y) * Math.min(1, dt * 14);
        if (st.specialTimer <= 0 && missing > 0) { st.absorbTimer = ROSE_ABSORB_TIME; continue; }
      } else {
        st.x += (tx - st.x) * Math.min(1, dt * 14);
        st.y += (ty - st.y) * Math.min(1, dt * 14);
      }
      if (def.healPerSec && p.hp < p.maxHp) {
        const threshold = def.healPerSecThreshold ?? 1;
        if (p.hp / p.maxHp < threshold) {
          const restored = Math.min(p.maxHp - p.hp, def.healPerSec * rarityMult(cell.rarity) * dt);
          if (restored > 0) { p.hp += restored; p.statsDirty = true; }
        }
      }
      if (def.shieldPerSec) {
        const maxShield = p.maxHp;
        if (p.shield < maxShield) { p.shield = Math.min(maxShield, p.shield + def.shieldPerSec * rarityMult(cell.rarity) * dt); p.statsDirty = true; }
      }
      const dmg = def.damage * rarityMult(cell.rarity);
      // Moon radius x4: both collision and visual are scaled up 4x.
      const isMoonRadius = (def.name ?? "").toLowerCase().includes("moon");
      const pr = def.radius * (1 + cell.rarity * 0.06) * (isMoonRadius ? 4 : 1);
      let targetMob: Mob | null = null;
      let targetDist = Infinity;
      let totalIncoming = 0;
      for (const mob of world.mobs) {
        if (mob.friendly) continue;
        this.collisionCounter.n++;
        const d = Math.hypot(mob.x - st.x, mob.y - st.y);
        if (d >= mob.radius + pr) continue;
        totalIncoming += mob.damage * 0.5;
        if (d < targetDist) { targetDist = d; targetMob = mob; }
      }
      if (targetMob && st.hitCd <= 0) {
        targetMob.hp -= dmg;
        targetMob.lastHitBy = p.id;
        targetMob.targetId = p.id;
        targetMob.addDamage(p.id, dmg);
        st.hp -= totalIncoming;
        st.hitCd = 0.25;
        const kb = 90 / (targetMob.radius / 20);
        targetMob.vx += ((targetMob.x - st.x) / (targetDist || 1)) * kb;
        targetMob.vy += ((targetMob.y - st.y) / (targetDist || 1)) * kb;
        if (st.hp <= 0) {
          st.alive = false; st.timer = def.reload; st.specialTimer = 0; st.absorbTimer = 0;
          if (isSummon) this.despawnPets(p, i);
        }
      }
    }
  }

  private cleanupPets(p: Player, slot: number) {
    const pets = p.pets[slot] || [];
    const active: Mob[] = [];
    for (const pet of pets) {
      if (pet && pet.hp > 0 && pet.mapId === p.mapId) active.push(pet);
      else if (pet) { const w = this.worlds[pet.mapId]; if (w) w.mobs = w.mobs.filter((m) => m !== pet); }
    }
    p.pets[slot] = active;
  }

  private hatchPet(p: Player, slot: number, cell: Cell) {
    const def = ITEMS[cell.item];
    if (def.petMob === undefined) return;
    const pets = p.pets[slot] || [];
    const room = getSummonCount(cell.item) - pets.length;
    const toSpawn = Math.min(getSummonBatch(cell.item), Math.max(0, room));
    if (toSpawn <= 0) return;
    const rarity = this.getSummonRarityWithDna(p, cell);
    const protection = getSpawnProtection(cell.item);
    const map = MAPS[p.mapId];
    for (let i = 0; i < toSpawn; i++) {
      const angle = Math.random() * Math.PI * 2;
      const dist = 40 + Math.random() * 30;
      const x = clamp(p.x + Math.cos(angle) * dist, 40, map.width - 40);
      const y = clamp(p.y + Math.sin(angle) * dist, 40, map.height - 40);
      const m = new Mob(this.nextId++, def.petMob, p.mapId, x, y, rarity, true);
      m.ownerId = p.id; m.ownerSlot = slot; m.sourceItem = cell.item; m.sourceRarity = cell.rarity;
      m.maxHp = Math.round(m.maxHp * 1.4); m.hp = m.maxHp;
      if (m.speed > 0) m.speed = Math.max(70, m.speed * 1.5);
      m.spawnProtection = protection;
      this.worlds[p.mapId].mobs.push(m);
      pets.push(m);
    }
    p.pets[slot] = pets;
  }

  private getSummonRarityWithDna(p: Player, cell: Cell): number {
    const def = ITEMS[cell.item];
    if (!def || def.kind !== "summon") return 0;
    const summonRarity = Math.max(0, Math.min(MAX_RARITY, cell.rarity));
    const mappedRarity = def.noDowngrade ? summonRarity : mapRarityToSummonRarity(summonRarity);
    let hasValidDna = false;
    const cloverRarities: number[] = [];
    for (let i = 0; i < SLOT_COUNT; i++) {
      const other = p.slots[i];
      if (!other) continue;
      const otherDef = ITEMS[other.item];
      const st = p.petals[i];
      const broken = st ? !st.alive : false;
      if (broken) continue;
      if (otherDef.kind === "dna" && other.rarity >= summonRarity) hasValidDna = true;
      if (other.item === CLOVER_ITEM) cloverRarities.push(other.rarity);
    }
    if (!hasValidDna) return mappedRarity;
    const totalChance = Math.min(1, DNA_UPGRADE_BASE_CHANCE + cloverDnaBonus(cloverRarities));
    if (Math.random() < totalChance && mappedRarity < MAX_RARITY) return mappedRarity + 1;
    return mappedRarity;
  }
private updateWorld(mapId: number, dt: number, players: Player[]) {
  const map = MAPS[mapId];
  const world = this.worlds[mapId];
  const collider = this.wallColliders[mapId];
  const here = players.filter((p) => p.mapId === mapId && p.alive);

  // ===== ✅ 视野裁剪范围 =====
  const VIEW_RADIUS = 1300; // 只处理玩家周围 2000 像素内的生物
  const VIEW_RADIUS_SQ = VIEW_RADIUS * VIEW_RADIUS;

  // ===== 构建玩家位置集合（用于快速距离检查） =====
  const playerPositions = here.map(p => ({ x: p.x, y: p.y }));

  // ===== 空间网格 =====
  const MOB_CELL_SIZE = 250;
  const mobGrid = new Map<string, Mob[]>();
  const getKey = (x: number, y: number) => `${Math.floor(x / MOB_CELL_SIZE)},${Math.floor(y / MOB_CELL_SIZE)}`;

  for (const mob of world.mobs) {
    const k = getKey(mob.x, mob.y);
    if (!mobGrid.has(k)) mobGrid.set(k, []);
    mobGrid.get(k)!.push(mob);
  }

  const getNearby = (x: number, y: number) => {
    const cx = Math.floor(x / MOB_CELL_SIZE), cy = Math.floor(y / MOB_CELL_SIZE);
    const r: Mob[] = [];
    for (let dx = -1; dx <= 1; dx++) {
      for (let dy = -1; dy <= 1; dy++) {
        const c = mobGrid.get(`${cx + dx},${cy + dy}`);
        if (c) r.push(...c);
      }
    }
    return r;
  };

  for (let i = world.mobs.length - 1; i >= 0; i--) {
    const mob = world.mobs[i];

    // ===== ✅ 检查是否在玩家视野内 =====
    let inView = false;
    // 玩家召唤物始终在视野内
    if (mob.ownerId !== 0) {
      inView = true;
    } else {
      for (const pos of playerPositions) {
        const dx = mob.x - pos.x;
        const dy = mob.y - pos.y;
        if (dx * dx + dy * dy < VIEW_RADIUS_SQ) {
          inView = true;
          break;
        }
      }
    }

    // ===== ✅ 如果不在视野内，只做基础更新（不进行碰撞检测） =====
    if (!inView) {
      // 仍然移动和更新
      mob.x += mob.vx * dt;
      mob.y += mob.vy * dt;
      mob.x = clamp(mob.x, mob.radius, map.width - mob.radius);
      mob.y = clamp(mob.y, mob.radius, map.height - mob.radius);


      // 减少生命值恢复（可选）
      if (mob.hp < mob.maxHp) {
        mob.hp = Math.min(mob.maxHp, mob.hp + 0.1 * dt);
      }
      continue; // 跳过碰撞检测
    }

    // ===== 视野内的生物：完整更新 =====
    mob.hitCd = Math.max(0, mob.hitCd - dt);
    mob.spawnProtection = Math.max(0, mob.spawnProtection - dt);


    // ---- 目标寻找 ----
    let target: { x: number; y: number; id: number } | null = null;
    let best = Infinity;

    if (mob.friendly) {
      for (const other of world.mobs) {
        if (!other.friendly) {
          const d = Math.hypot(other.x - mob.x, other.y - mob.y);
          if (d < 520 && d < best) { best = d; target = other; }
        }
      }
      const owner = here.find((p) => p.id === mob.ownerId);
      if (owner) {
        const od = Math.hypot(owner.x - mob.x, owner.y - mob.y);
        if (!target || od > 260) target = { x: owner.x, y: owner.y, id: owner.id };
      }
    } else {
      for (const p of here) {
        const d = Math.hypot(p.x - mob.x, p.y - mob.y);
        if (d < 460 && d < best) { best = d; target = { x: p.x, y: p.y, id: p.id }; }
      }
      for (const other of world.mobs) {
        if (other.friendly) {
          const d = Math.hypot(other.x - mob.x, other.y - mob.y);
          if (d < 380 && d < best) { best = d; target = other; }
        }
      }
    }

    // ---- 移动 ----
    if (target && mob.speed > 0) {
      const dx = target.x - mob.x, dy = target.y - mob.y, d = Math.hypot(dx, dy) || 1;
      mob.vx += ((dx / d) * mob.speed - mob.vx) * Math.min(1, dt * 4);
      mob.vy += ((dy / d) * mob.speed - mob.vy) * Math.min(1, dt * 4);
      mob.angle = Math.atan2(dy, dx);
    } else if (mob.speed > 0) {
      mob.wander -= dt;
      if (mob.wander <= 0) {
        mob.wander = 1.5 + Math.random() * 3;
        mob.angle = Math.random() * Math.PI * 2;
      }
      mob.vx += (Math.cos(mob.angle) * mob.speed * 0.4 - mob.vx) * Math.min(1, dt * 2);
      mob.vy += (Math.sin(mob.angle) * mob.speed * 0.4 - mob.vy) * Math.min(1, dt * 2);
    } else {
      mob.vx *= 0.9;
      mob.vy *= 0.9;
    }

    // ---- 位置更新 ----
    mob.x += mob.vx * dt;
    mob.y += mob.vy * dt;
    mob.x = clamp(mob.x, mob.radius, map.width - mob.radius);
    mob.y = clamp(mob.y, mob.radius, map.height - mob.radius);
    // Mob 墙壁碰撞已移至 wallCollisionBatch() 以 20fps 批量处理

    // ---- 生物间碰撞 ----
    const nearby = getNearby(mob.x, mob.y);
    for (const other of nearby) {
      if (other === mob) continue;
      this.collisionCounter.n++;
      const dx = mob.x - other.x, dy = mob.y - other.y, d = Math.hypot(dx, dy), min = mob.radius + other.radius;
      if (d < min && d > 0.001) {
        const push = (min - d) * 0.4;
        mob.x += (dx / d) * push;
        mob.y += (dy / d) * push;

        // ---- 敌对生物攻击 ----
        if (mob.friendly !== other.friendly && mob.hitCd <= 0) {
          const attacker = mob.friendly ? mob : other;
          const victim = mob.friendly ? other : mob;
          if (victim.spawnProtection <= 0) {
            const dmg = attacker.damage * 0.6;
            victim.hp -= dmg;
            victim.lastHitBy = attacker.ownerId;
            if (!victim.friendly && attacker.friendly && attacker.ownerId) {
              victim.addDamage(attacker.ownerId, dmg);
            }
          }
          if (attacker.spawnProtection <= 0) {
            attacker.hp -= victim.damage * 0.3;
          }
          mob.hitCd = 0.1;
          other.hitCd = 0.1;
        }
      }
    }

    // ---- 生物攻击玩家 ----
    if (!mob.friendly) {
      for (const p of here) {
        this.collisionCounter.n++;
        const d = Math.hypot(p.x - mob.x, p.y - mob.y);
        if (d < mob.radius + PLAYER_RADIUS) {
          const push = (mob.radius + PLAYER_RADIUS - d) * 0.5;
          const ux = (p.x - mob.x) / (d || 1), uy = (p.y - mob.y) / (d || 1);
          p.x += ux * push;
          p.y += uy * push;
          mob.x -= ux * push * 0.4;
          mob.y -= uy * push * 0.4;

          if (p.hurtCd <= 0) {
            let dmg = mob.damage;
            if (p.shield > 0 && dmg > 0) {
              const absorbed = Math.min(p.shield * 2, dmg);
              p.shield -= absorbed / 2;
              dmg -= absorbed;
            }
            p.hp -= dmg;
            p.hurtCd = 0.1;
            p.statsDirty = true;
            const c = this.clientOf(p.id);
            if (c) this.pushEvent(c, EVT.HIT, p.x, p.y, Math.round(mob.damage));
            if (p.hp <= 0) this.killPlayer(p);
          }
        }
      }
    }

    // ---- Spawner 逻辑 ----
    if (!mob.friendly) {
      const mobDef = MOBS[mob.type];
      if (mobDef.spawner) {
        const hpPct = mob.hp / mob.maxHp;
        for (const threshold of mobDef.spawner.thresholds) {
          if (hpPct <= threshold && !mob.spawnedThresholds.has(threshold)) {
            mob.spawnedThresholds.add(threshold);
            for (const spawnId of mobDef.spawner.spawnMobs(mob.rarity)) {
              const spawnDef = MOBS[spawnId];
              if (!spawnDef) continue;
              const angle = Math.random() * Math.PI * 2;
              const dist = mob.radius + spawnDef.radius + 12 + Math.random() * 28;
              let sx = mob.x + Math.cos(angle) * dist;
              let sy = mob.y + Math.sin(angle) * dist;
              sx = clamp(sx, spawnDef.radius + 4, map.width - spawnDef.radius - 4);
              sy = clamp(sy, spawnDef.radius + 4, map.height - spawnDef.radius - 4);
              const [rx, ry] = collider.collideCircle(sx, sy, spawnDef.radius + 4);
              world.mobs.push(new Mob(this.nextId++, spawnId, mapId, rx, ry, mob.rarity));
            }
          }
        }
      }
    }

    // ---- 死亡处理 ----
    if (mob.hp <= 0) {
      world.mobs.splice(i, 1);
      if (mob.friendly) {
        const owner = here.find((p) => p.id === mob.ownerId);
        if (owner && mob.ownerSlot >= 0) {
          owner.pets[mob.ownerSlot] = (owner.pets[mob.ownerSlot] || []).filter((m) => m !== mob);
        }
        continue;
      }
      this.onMobKilled(mob, mapId);
      continue;
    }
  }

  // ---- 掉落物更新 ----
  for (let i = world.drops.length - 1; i >= 0; i--) {
    const d = world.drops[i];
    d.ttl -= dt;
    if (d.ttl <= 0) world.drops.splice(i, 1);
  }

  // ---- 生成新生物 ----
  const hostiles = world.mobs.filter((m) => !m.friendly).length;
  if (hostiles < this.mobCapForMap(mapId) && Math.random() < 0.5) {
    this.spawnMob(mapId);
  }
}
  private setBonusStatus(p: Player, multiplier: number, seconds: number) {
    const safeMultiplier = Math.max(1, Math.min(5, Math.floor(multiplier)));
    const safeSeconds = Math.max(0, Math.min(60 * 60, Math.floor(seconds)));
    p.bonusMultiplier = safeSeconds > 0 ? safeMultiplier : 1;
    p.bonusEndsAt = safeSeconds > 0 ? Date.now() + safeSeconds * 1000 : 0;
  }

  private dropMultiplierFor(p: Player | null): number {
    if (!p || p.bonusEndsAt <= Date.now()) return 1;
    return p.bonusMultiplier;
  }

  private magicCoreRarity(p: Player | null): number {
    if (!p || MAGIC_CORE_ITEM < 0) return -1;
    let best = -1;
    for (let i = 0; i < SLOT_COUNT; i++) {
      const cell = p.slots[i];
      if (cell && cell.item === MAGIC_CORE_ITEM && cell.rarity > best) best = cell.rarity;
    }
    return best;
  }

  private computeEligibleLooters(mob: Mob): Set<number> {
    const eligible = new Set<number>();
    const maxHp = mob.maxHp > 0 ? mob.maxHp : 1;
    const perPlayerThreshold = maxHp * 0.05;
    const playerToSquadCode = new Map<number, string>();
    for (const [code, squad] of this.squads.entries()) { for (const pid of squad.members.keys()) playerToSquadCode.set(pid, code); }
    for (const squad of this.squads.values()) {
      const memberIds = Array.from(squad.members.keys());
      if (memberIds.length === 0) continue;
      let total = 0;
      for (const pid of memberIds) total += mob.damageByPlayer.get(pid) || 0;
      const required = perPlayerThreshold * memberIds.length;
      if (total >= required) { for (const pid of memberIds) eligible.add(pid); }
    }
    for (const [pid, dmg] of mob.damageByPlayer.entries()) {
      if (playerToSquadCode.has(pid)) continue;
      if (dmg >= perPlayerThreshold) eligible.add(pid);
    }
    return eligible;
  }

  private onMobKilled(mob: Mob, mapId: number) {
    if (mob.friendly) return;
    const def = MOBS[mob.type];
    const world = this.worlds[mapId];
    const killerClient = mob.lastHitBy ? this.clientOf(mob.lastHitBy) : null;
    const killer = killerClient?.player ?? null;
    if (killer) {
      const xp = Math.round(def.xp * (1 + mob.rarity * 0.9));
      killer.xp += xp; this.applyLevel(killer); killer.statsDirty = true;
      this.pushEvent(killerClient!, EVT.XP, mob.x, mob.y, xp);
      this.pushEvent(killerClient!, EVT.KILL, mob.x, mob.y, mob.type, EMPTY_ITEM, mob.rarity);
    }
    if (world.drops.length >= MAX_DROPPED_CARDS) { world.drops.splice(0, DROP_TRIM_COUNT); }
    const mobRarityIndex = Math.max(0, Math.min(MAX_RARITY, mob.rarity));
    const mobRarityName = RARITIES[mobRarityIndex].name;
    const rarityIndexOf = (name: string) => Math.max(0, Math.min(MAX_RARITY, RARITIES.findIndex((r) => r.name === name)));
    // Per-player loot: each eligible looter gets their own private copy of every
    // drop. Non-squad players only see their own drops; squad members each get
    // an independent copy so everyone gets loot without stealing.
    const eligibleLooters = this.computeEligibleLooters(mob);
    if (eligibleLooters.size === 0) return;
    for (const looterId of eligibleLooters) {
      const looterClient = this.clientOf(looterId);
      const looterPlayer = looterClient?.player ?? null;
      const looterDropMult = this.dropMultiplierFor(looterPlayer);
      const looterCoreRarity = this.magicCoreRarity(looterPlayer);
      const rolled: { item: number; rarity: number; dropNum: number }[] = [];
      for (const drop of def.drops) {
        for (let i = 0; i < looterDropMult; i++) {
          let item = drop.item;
          let rarity = rarityIndexOf(getDropRarityByItem(drop.item, mobRarityName));
          const magicItem = MAGIC_ITEM_MAP[drop.item];
          if (magicItem !== undefined && looterCoreRarity >= 0) {
            const magicRarity = rarityIndexOf(getDropRarityByItem(magicItem, mobRarityName));
            if (magicRarity > 0) { item = magicItem; rarity = Math.min(magicRarity, looterCoreRarity); }
          }
          rolled.push({ item, rarity, dropNum: i });
        }
      }
      rolled.forEach((roll) => {
        const angle = Math.random() * Math.PI * 2;
        const distance = (Math.random() * 20 + 10) * (1 + roll.dropNum * 0.5);
        const x = mob.x + Math.cos(angle) * distance;
        const y = mob.y + Math.sin(angle) * distance;
        // Private drop: only this looter can see and loot it.
        this.spawnDrop(mapId, roll.item, roll.rarity, x, y, looterId, new Set([looterId]));
      });
    }
  }

  private setsEqual(a: Set<number> | null, b: Set<number> | null): boolean {
    if (a === b) return true; if (!a || !b) return false; if (a.size !== b.size) return false;
    for (const v of a) if (!b.has(v)) return false;
    return true;
  }

  private spawnDrop(mapId: number, item: number, rarity: number, x: number, y: number, ownerId: number, allowed: Set<number> | null = null) {
    const world = this.worlds[mapId];
    for (const d of world.drops) {
      if (d.item !== item || d.rarity !== rarity || d.count >= DROP_STACK_MAX) continue;
      if (Math.hypot(d.x - x, d.y - y) > DROP_STACK_RADIUS) continue;
      if (!this.setsEqual(d.allowedPlayerIds, allowed)) continue;
      d.count++; d.ttl = Math.max(d.ttl, 45);
      if (d.ownerId !== ownerId) d.ownerId = 0;
      return;
    }
    const nd = new Drop(this.nextId++, mapId, x, y, item, rarity, ownerId);
    nd.allowedPlayerIds = allowed ? new Set(allowed) : null;
    world.drops.push(nd);
  }

  private killPlayer(p: Player) {
    p.alive = false; p.hp = 0; p.shield = 0; p.statsDirty = true;
    const world = this.worlds[p.mapId];
    world.mobs = world.mobs.filter((m) => m.ownerId !== p.id);
    for (let i = 0; i < SLOT_COUNT; i++) p.pets[i] = [];
    const c = this.clientOf(p.id);
    if (c) this.pushEvent(c, EVT.DEATH, p.x, p.y, p.level);
  }

  private magnetRangeFor(p: Player): number {
    const MAGNET_RARITY_BONUS = [0, 1, 1.2, 2, 2.5, 3, 4.5, 6, 9, 14, 14];
    let total = 0;
    for (let i = 0; i < SLOT_COUNT; i++) {
      const cell = p.slots[i];
      if (!cell) continue;
      const def = ITEMS[cell.item];
      if (!def.magnetRange) continue;
      const st = p.petals[i];
      if (st && !st.alive) continue;
      const bonus = MAGNET_RARITY_BONUS[Math.min(cell.rarity, MAGNET_RARITY_BONUS.length - 1)] ?? 0;
      total += Math.round(def.magnetRange + bonus * 150);
    }
    return total;
  }

  private pickupDrops(p: Player) {
    if (!p.alive) return;
    const world = this.worlds[p.mapId];
    const magnetRange = this.magnetRangeFor(p);
    let looted = 0;
    for (let i = world.drops.length - 1; i >= 0; i--) {
      const d = world.drops[i];
      // Per-player filtering: if the drop has an allow-list, only that player
      // can see and loot it. null = legacy/anyone (shouldn't happen in new code).
      if (d.allowedPlayerIds !== null && d.allowedPlayerIds !== undefined && !d.allowedPlayerIds.has(p.id)) continue;
      const dist = Math.hypot(d.x - p.x, d.y - p.y);
      if (magnetRange > 0 && dist < magnetRange && dist > 46) {
        const pull = Math.min(Math.min(1, 8 / dist) * 120, dist - 46);
        d.x += ((p.x - d.x) / dist) * pull;
        d.y += ((p.y - d.y) / dist) * pull;
      }
      if (dist < 46) {
        if (this.addItem(p, d.item, d.rarity, d.count)) {
          world.drops.splice(i, 1);
          const c = this.clientOf(p.id);
          if (c) this.pushEvent(c, EVT.LOOT, d.x, d.y - (looted++ % 3) * 18, 0, d.item, d.rarity);
        }
      }
    }
  }

  // ------------------------------------------------------------ state sync
  private sendState(c: ClientState) {
    const p = c.player;
    if (!p) return;
    const world = this.worlds[p.mapId];
    const w = new Writer(64);
    w.u8(S2C.SNAPSHOT).u32(this.tickCount);
    let count = 0;
    const viewX = 1300;
    const viewY = 950;
    const inView = (x: number, y: number) => Math.abs(x - p.x) < viewX && Math.abs(y - p.y) < viewY;
    const body = new Writer(65536);
    for (const other of this.clients.values()) {
      const op = other.player;
      if (!op || op.mapId !== p.mapId || !op.alive) continue;
      if (op !== p && !inView(op.x, op.y)) continue;
      body.u8(ENT.PLAYER).u16(op.id).u8(op.flags).u8(op === p ? TEAM.SELF : TEAM.FRIENDLY)
        .i16(Math.round(op.x)).i16(Math.round(op.y))
        .u16(Math.round(((op.baseAngle % (Math.PI * 2)) / (Math.PI * 2)) * 65535))
        .u8(Math.round(PLAYER_RADIUS)).u8(Math.round((op.hp / op.maxHp) * 255)).str(op.name);
      count++;
      for (let i = 0; i < SLOT_COUNT; i++) {
        const cell = op.slots[i];
        const st = op.petals[i];
        if (!cell || !st || !st.alive) continue;
        if (!orbitsAsPetal(ITEMS[cell.item].kind)) continue;
        body.u8(ENT.PETAL).u16(st.id).u8(cell.item).u8(cell.rarity)
          .i16(Math.round(st.x)).i16(Math.round(st.y)).u16(0)
          .u8(Math.round(ITEMS[cell.item].radius * (1 + cell.rarity * 0.06) * ((ITEMS[cell.item].name ?? "").toLowerCase().includes("moon") ? 4 : 1)))
          .u8(Math.round((st.hp / st.maxHp) * 255));
        count++;
      }
    }
    for (const mob of world.mobs) {
      if (!inView(mob.x, mob.y)) continue;
      body.u8(ENT.MOB).u16(mob.id).u8(mob.type)
        .u8(mob.friendly ? (mob.ownerId === p.id ? TEAM.SELF : TEAM.FRIENDLY) : TEAM.HOSTILE)
        .i16(Math.round(mob.x)).i16(Math.round(mob.y))
        .u16(Math.round((((mob.angle % (Math.PI * 2)) + Math.PI * 2) % (Math.PI * 2) / (Math.PI * 2)) * 65535))
        .u16(Math.min(65535, Math.round(mob.radius)))
        .u8(Math.max(0, Math.round((mob.hp / mob.maxHp) * 255))).u8(mob.rarity);
      count++;
    }
    // Drops: only send those the player is allowed to see/loot.
    for (const d of world.drops) {
      if (!inView(d.x, d.y)) continue;
      // Per-player drops: skip this drop if the player is not in its allow-list.
      if (d.allowedPlayerIds !== null && d.allowedPlayerIds !== undefined && !d.allowedPlayerIds.has(p.id)) continue;
      body.u8(ENT.DROP).u16(d.id).u8(d.item).u8(d.rarity)
        .i16(Math.round(d.x)).i16(Math.round(d.y)).u16(0).u8(12).u8(Math.min(255, d.count));
      count++;
    }
    for (let i = 0; i < SLOT_COUNT; i++) {
      const cell = p.slots[i];
      const st = p.petals[i];
      const def = cell ? ITEMS[cell.item] : null;
      if (!cell || !st || !def || !orbitsAsPetal(def.kind) || st.alive) { body.u8(255); continue; }
      const total = def.reload > 0 ? def.reload : 1;
      body.u8(Math.round((1 - Math.max(0, Math.min(1, st.timer / total))) * 255));
    }
    for (let i = 0; i < SLOT_COUNT; i++) {
      const cell = p.slots[i];
      const st = p.petals[i];
      if (!cell || !st || !st.alive) { body.u8(255); continue; }
      body.u8(Math.max(0, Math.min(255, Math.round((st.hp / Math.max(1, st.maxHp)) * 255))));
    }
    w.u16(count);
    const head = w.bytes(), tail = body.bytes();
    const packet = new Uint8Array(head.length + tail.length);
    packet.set(head, 0); packet.set(tail, head.length);
    c.send(packet);
    if (p.dirty) {
      p.dirty = false;
      const iw = new Writer(256);
      iw.u8(S2C.INVENTORY).u8(SLOT_COUNT);
      for (const cell of p.slots) writeCell(iw, cell);
      iw.u8(SECONDARY_SLOT_COUNT);
      for (let i = 0; i < SECONDARY_SLOT_COUNT; i++) writeCell(iw, p.secondary[i] ?? null);
      let bagLen = p.bag.length;
      while (bagLen > BAG_COUNT && !p.bag[bagLen - 1]) bagLen--;
      iw.u16(bagLen);
      for (let i = 0; i < bagLen; i++) writeCell(iw, p.bag[i] ?? null);
      c.send(iw.bytes());
    }
    if (p.statsDirty || this.tickCount % 10 === 0) {
      p.statsDirty = false;
      const now = Date.now();
      const oracleSecLeft = Math.max(0, Math.ceil((p.nextOracleAt - now) / 1000));
      const tradeSecLeft = Math.max(0, Math.ceil((p.nextTradeAt - now) / 1000));
      const sw = new Writer(28);
      sw.u8(S2C.STATS).u32(p.xp).u16(p.level).u16(Math.max(0, Math.round(p.hp))).u16(Math.round(p.maxHp))
        .u8(p.mapId).u8(p.alive ? 1 : 0).u32(oracleSecLeft).u32(tradeSecLeft).u16(Math.max(0, Math.round(p.shield)));
      c.send(sw.bytes());
    }
    if (this.tickCount % 20 === 0) {
      const dw = new Writer(10);
      dw.u8(S2C.DEBUG).u32(this.collisionCounter.n).u16(Math.min(65535, this.entityCount())).u16(Math.min(65535, this.playerCount()));
      c.send(dw.bytes());
    }
    for (const e of c.events) c.send(e);
    c.events.length = 0;
  }
}

function writeCell(w: Writer, cell: Cell | null) {
  if (!cell || cell.count <= 0) w.u8(EMPTY_ITEM).u8(0).u16(0);
  else w.u8(cell.item).u8(cell.rarity).u16(Math.min(65535, cell.count));
}

function readCell(r: Reader): Cell | null {
  const item = r.u8();
  const rarity = r.u8();
  const count = r.u16();
  if (item === EMPTY_ITEM || count <= 0 || item >= ITEMS.length) return null;
  return { item, rarity: Math.min(rarity, MAX_RARITY), count };
}

export { writeCell, readCell };
